# -*- coding: utf-8 -*-
"""TtoF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2xAm10NjSKI5hy-NM2-ZtWehE-fmPvn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url = "https://github.com/Lun-Tsan/Introduction-to-Engineering-Science-and-Ocean-Engineering-Class-Assignment/blob/master/3000seconds_Ethernet_signal.csv?raw=true"
df = pd.read_csv(url,header=None,skiprows=1)

df_split = df[0].str.split(',',expand=True)
df_split.columns = ['Interval start','All Packets','TCP Errors']

df_split['Interval start'] = pd.to_numeric(df_split['Interval start'])
df_split['All Packets'] = pd.to_numeric(df_split['All Packets'])
df_split['TCP Errors'] = pd.to_numeric(df_split['TCP Errors'])

fig, axs = plt.subplots(2, 2, figsize=(14, 10))

############################################################
####       Packets over Time         #####
############################################################
time_data = df_split['All Packets'].values

axs[0, 0].plot(df_split['Interval start'], time_data)
axs[0, 0].set_title('Time Domain: Packets over Time')
axs[0, 0].set_xlabel('Time (s)')
axs[0, 0].set_ylabel('Packets Count')

time_data = time_data - np.mean(time_data)
fft = np.fft.fft(time_data)
frequencies = np.fft.fftfreq(len(time_data), df_split['Interval start'].diff().mean())
magnitude = np.abs(fft)

axs[0, 1].plot(frequencies[:len(time_data)//2], magnitude[:len(time_data)//2])
axs[0, 1].set_title('Frequency Domain: Packets')
axs[0, 1].set_xlabel('Frequency (Hz)')
axs[0, 1].set_ylabel('Magnitude')


############################################################
####       TCP Errors over Time       #####
############################################################
error_data = df_split['TCP Errors'].values

axs[1, 0].plot(df_split['Interval start'], error_data)
axs[1, 0].set_title('Time Domain: TCP Errors over Time')
axs[1, 0].set_xlabel('Time (s)')
axs[1, 0].set_ylabel('Packets Count')

error_data = error_data - np.mean(error_data)
fft = np.fft.fft(error_data)
frequencies = np.fft.fftfreq(len(error_data), df_split['Interval start'].diff().mean())
magnitude = np.abs(fft)

axs[1, 1].plot(frequencies[:len(error_data)//2], magnitude[:len(error_data)//2])
axs[1, 1].set_title('Frequency Domain: TCP Errors')
axs[1, 1].set_xlabel('Frequency (Hz)')
axs[1, 1].set_ylabel('Magnitude')

plt.tight_layout()
plt.show()